#!/bin/bash

sed -i "$s/.*/colors = Natura/" "$HOME/.config/qtile/settings/pallete.py"
cp -r ~/Themes/Natura/. ~/Themes/Natura/.zshrc ~/ &&
feh --bg-scale  ~/Wallpaper/claudio-testa-FrlCwXwbwkk-unsplash.jpg &&
sed -i '$s/.*/feh --bg-scale "~/Wallpaper/claudio-testa-FrlCwXwbwkk-unsplash.jpg"/' "$HOME/.config/qtile/autostart_once.sh"
qtile cmd-obj -o cmd -f restart 

